language: python
python:
  - 3.6
before_install:
  - nvm use stable
  - npm install -g yarn
install:
  - yarn
  - pip -e .
script:
  - python javiergr/freezer.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  fqdn: javier.gr
  on:
    branch: master